version: '3.8'

networks:
    my_network:
      name: my_network
      external: false

services:
    vue-oauth-sample:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: vue-oauth-sample
        ports:
            - 80:80
        deploy:
            restart_policy:
                condition: any
        networks:
        - my_network