version: '3.8'

networks:
  my_network:
    name: my_network
    external: false

services:
  web-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-app
    image: web-app-sample:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: any
    networks:
      - my_network
